### ISSUE TITLE
iOS APNS Bad Device Token

### ISSUE THREAD

**Issue by HyuArzani** [CleverTap/clevertap-react-native#23]
Hey when i want to integrate clevertap on ios using firebase FCM and then when i try to create campaign on ios  i get error on clevertap dashboard:

<img width="1089" alt="screen shot 2018-11-06 at 15 03 19" src="https://user-images.githubusercontent.com/27977978/48050695-2fbd0300-e1d5-11e8-848c-151a8f436c1a.png">

also how we get the APNs device token to test push notification, i try using FCM token it was failed with bad APNs token also, when i try generate device token from appDelegat.m

- (void)application:(UIApplication *)app didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
  NSString *token = [[deviceToken description] stringByTrimmingCharactersInSet: [NSCharacterSet characterSetWithCharactersInString:@"<>"]];
  token = [token stringByReplacingOccurrencesOfString:@" " withString:@""];
  NSLog(@"content---%@", token);
}

no log came out, i think the function not working, dunno

**Comment by Aditi3** [comment]
Hey @HyuArzani, 

To implement push notifications in iOS React Native, please check included ExampleProject.js: https://github.com/CleverTap/clevertap-react-native/blob/master/ExampleProject/ExampleProject.js

Here you can see, by calling the below method:

// for iOS only: register for push notifications CleverTap.registerForPush();

you can enable support for push notifications.

**Comment by HyuArzani** [comment]
Hi, for CleverTap.registerForPush() only log inside function, is it enable to give callback device APNs token when success and error when fail happened, i'm using clevertap with firebase fcm, is it the notification setting get conflict with firebase setting? I've test with android and its fine, i need to implement clevertap with firebase fcm also

**Comment by Aditi3** [comment]
Hey, 

Enabling push notifications using FCM token is not supported for iOS.  
You need to send APNS token to CleverTap for sending notification successfully to the iOS device.

**Comment by Aditi3** [comment]
Hey @HyuArzani,

Not required to remove FCM notifications for your application and the only necessity is to pass the APNs (Apple Push Notifications) token because iOS does not detect FCM token that is why it is not able to recognize the user and the user is unreachable.

You can achieve the same by using the below code snippet, the code enables the support for push notifications, fetch the apns device and send it to the CleverTap.

// for iOS only: register for push notifications
`CleverTap.registerForPush();`

Make sure, you're calling the above method before registering for FCM.

Using `CleverTap.registerPush();` it should be working without removing the project from Firebase for your application.

**Comment by HyuArzani** [comment]
ok, i think i get it, it was my mistake when upload the .p12 key, so for debug mode we must use development .p12, haven't check on release mode, anyway could we give CleverTap.registerForPush(); callback like promise that give the APNs device token on success and throw error on fail to register? i mean if it possible tough, closing for now

**Comment by AbhishekTF2020** [comment]
CleverTap.registerPush()
This method is not available now
also i have upload p8 for dev and prod still issue persist.
As dashboard is not accepting p12 which is working i cross checked

**Comment by melvinmt** [comment]
> ok, i think i get it, it was my mistake when upload the .p12 key, so for debug mode we must use development .p12, haven't check on release mode, anyway could we give CleverTap.registerForPush(); callback like promise that give the APNs device token on success and throw error on fail to register? i mean if it possible tough, closing for now

I would like to second this request. 

> Make sure, you're calling the above method before registering for FCM.

We are also trying to combine FCM with Clevertap push permissions and it has been very error prone so far. It gets worse without a callback or promise because we can't tell whether Clevertap push notification succeeded before we request FCM permission.

**Comment by DivyaJariwala610** [comment]
@Aditi3 I have used CleverTap.registerPush() before registering for FCM but still getting the same error. Also checked both approach  APNS key and certificate.
