### ISSUE TITLE
Android App Not Detecting Push Notification Click Events in Killed State

### ISSUE THREAD

**Issue by mihailapuste** [CleverTap/clevertap-react-native#366]
### Description
On Android, our app is unable to detect click events from push notifications when launched from a killed state. The event detection works as expected when the app is in the background or foreground.

#### Code Reference
Based on the documentation provided [here](https://developer.clevertap.com/docs/react-native-push-notification), we have implemented the following:

#### `MainApplication.java`
```java
...

  @Override
  public void onCreate() {
    final String invocationEvent = BuildConfig.DEBUG ? "swipe" : "shake";

    CleverTapAPI.setDebugLevel(CleverTapAPI.LogLevel.VERBOSE);
    ActivityLifecycleCallback.register(this);

    super.onCreate();

    SoLoader.init(this, /* native exopackage */ false);

    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
      // If you opted-in for the New Architecture, we load the native entry point for this app.
      DefaultNewArchitectureEntryPoint.load();
    }

    ApplicationLifecycleDispatcher.onApplicationCreate(this);
  }

  ```
#### `MainActivity.java`

```java
  /**
   * Override which allows us to handle the push notification click event On Android 12 and onwards
   */
  @Override
  public void onNewIntent(Intent intent) {
      super.onNewIntent(intent);

      CleverTapAPI cleverTapDefaultInstance = CleverTapAPI.getDefaultInstance(getApplicationContext());
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
          if(cleverTapDefaultInstance != null) {
               cleverTapDefaultInstance.pushNotificationClickedEvent(intent.getExtras());
          }
      }
  }
```

#### `App.tsx`

```ts
import CleverTap from 'clevertap-react-native';

const App: React.FC = () => {

  useEffect(() => {
        CleverTap.registerForPush();

        androidNotificationChannels.forEach(
            ({ id, name, description, importance, showBadge }) => {
                CleverTap.createNotificationChannel(
                id,
                name,
                description,
                importance,
                showBadge,
                );
            },
            );

        CleverTap.addListener(
            CleverTap.CleverTapPushNotificationClicked,
            (event: any) => {
            log('Clevertap push notification clicked', event);

            callback?.(event);

            const deeplink = event?.wzrk_dl?.replace(`${deviceInfo.bundleId}://`, '');

            trackEvent('notification', {
                user_interaction: true,
                is_remote: true,
                source: 'clevertap',
                deeplink,
            });
            },
        );
  }, []);
...

```

### Final
While the implementation works flawlessly on iOS, Android does not register app opening events triggered by push notification clicks when the app is in a killed state. We would appreciate any assistance or insights into resolving this issue.

**Comment by shivamsharma2710** [comment]
Hi @mihailapuste 

Thank you for getting in touch with us.

Regarding your query, have you implemented the [document section](https://developer.clevertap.com/docs/react-native-push-notification#handle-notification-click-callback-when-the-app-is-terminated-or-killed) explaining how to receive callbacks when the **Android app is in the killed state**?

In that implementation, CleverTap SDK expects you to extend the `CleverTapApplication` class instead of the `Application` class in your `MainApplication.java`.

**Comment by mihailapuste** [comment]
@shivamsharma2710 
Thanks for the quick response.

I've added it to my `MainApplication.java.`, however I still have not been able to listen for the app opening event when in kill state. Do you have any other suggestions?

```java
import com.clevertap.react.CleverTapApplication;

public class MainApplication extends CleverTapApplication implements ReactApplication {
...
 @Override
  public void onCreate() {
    final String invocationEvent = BuildConfig.DEBUG ? "swipe" : "shake";

    CleverTapAPI.setDebugLevel(CleverTapAPI.LogLevel.VERBOSE);
    ActivityLifecycleCallback.register(this);

    super.onCreate();

    SoLoader.init(this, /* native exopackage */ false);

    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
      // If you opted-in for the New Architecture, we load the native entry point for this app.
      DefaultNewArchitectureEntryPoint.load();
    }

    ApplicationLifecycleDispatcher.onApplicationCreate(this);
  }
 ...
```

**Comment by shivamsharma2710** [comment]
@mihailapuste Have you used any FCM package in the `package.json`?

**Comment by mihailapuste** [comment]
> @mihailapuste Have you used any FCM package in the `package.json`?

@shivamsharma2710 do you mind sharing which package exactly? I haven't seen the need to install any other package other than the react native sdk.

**Comment by shivamsharma2710** [comment]
@mihailapuste 

No, you don't need to add any other package. I asked because you will need to change the placement of the `CleverTapPushNotificationClicked` callback from `App.tsx` to `index.js` if you have added the FCM package.

Besides that, could you please verify if you have registered the `MainApplication.java` class in the file correctly?

**Sample Code:**

 ```
<application
      android:name=".MainApplication"
      ..
 />
```

**Comment by shivamsharma2710** [comment]
@mihailapuste Thank you for the confirmation. Could you please verify if you have included the following package: https://rnfirebase.io/messaging/usage#installation?

**Comment by mihailapuste** [comment]
> @mihailapuste Thank you for the confirmation. Could you please verify if you have included the following package: https://rnfirebase.io/messaging/usage#installation?

@shivamsharma2710 

Added it to my package.json, no difference. Why would i need to install this? Wouldn't this be included in the SDK dependencies?

Also, even without that, I'm able to get my android to listen for events when the app is running, only having difficulties when app is killed.

**Comment by shivamsharma2710** [comment]
@mihailapuste no need to install the FCM package. I inquired about it as part of my investigation.

The FCM package creates a separate [Headless JS](https://reactnative.dev/docs/headless-js-android) service that operates independently of the main React component and does not mount the root component, causing interference with the `CleverTapPushNotificationClicked` callback invocation in the killed state.
However, it seems some other package is causing this behavior. 

As a workaround, please try placing the event registration in the **entry point(index.js)** instead of the **root component(App.tsx)** and let me know if it works.

**Comment by mihailapuste** [comment]
this seems to have worked. Thank you @shivamsharma2710

**Comment by shivamsharma2710** [comment]
@mihailapuste Could you please share the list of dependencies you've used in the **package.json**? This will help me identify the package that might be causing this behaviour. Thanks!

**Comment by shivamsharma2710** [comment]
> > As a workaround, please try placing the event registration in the entry point(index.js) instead of the root component(App.tsx) and let me know if it works.
> 
> this seems to have worked. Thank you @shivamsharma2710

Issue is resolved. Closing the ticket.

**Comment by chetank-syngenta** [comment]
@shivamsharma2710 Hope you're doing good. Same happened with me and after adding event listener in index.js it started working. Sharing my package.json with you to identify which package is causing this issue. Any further help is really appreciated. Thanks you in advance.
[package.json](https://github.com/user-attachments/files/15823171/package.json)

**Comment by shivamsharma2710** [comment]
Hi @chetank-syngenta 

I've gone through your package.json file. Please check [react-native-push-notification](https://www.npmjs.com/package/react-native-push-notification) package which might be creating a [Headless JS](https://reactnative.dev/docs/headless-js-android) service. You may refer to their [GitHub repo](https://github.com/zo0r/react-native-push-notification) for confirmation.

**Comment by chetank-syngenta** [comment]
Thanks for response @shivamsharma2710.
I tried removed all references of [react-native-push-notification](https://www.npmjs.com/package/react-native-push-notification) from package.json, AndroidMenifest.xml, build.gradle wherever it was used. Still facing same issue.
