### ISSUE TITLE
Push notification shown twice when app is in foreground

### ISSUE THREAD

**Issue by rickmed** [CleverTap/clevertap-react-native#404]
Happening in Android OS (ios untested).
clevertap-react-native: 2.2.1
com.clevertap.android:clevertap-android-sdk:6.2.1

Works correctly when app is in background or killed.

Screenshot below. Notice how one notification correctly renders the payload content (including going to the correct deep link when clicked and the other does not. The relevant notifications are the one with "tiigre".
![Screenshot (Aug 27, 2024 10_12_28 AM)](https://github.com/user-attachments/assets/f16ce1ad-d0bf-49a0-a8ea-6aadf1bd0e3b)

**Comment by rickmed** [comment]
logs:
```
08-27 12:37:11.825 25991 26746 D CleverTap:PushProvider:  [PushType:FCM] Found Valid Notification Message
08-27 12:37:11.826 25991 26746 V CleverTap:[:PushProvider:TEST-Z69-WWW-KI7B]:  [PushType:FCM] received notification from CleverTap: Bundle[{wzrk_acct_id=TEST-Z69-WWW-KI7B, nm=msg 2,
nt=title 2, omr_invoke_time_in_millis=1724776631826, wzrk_pivot=wzrk_default, wzrk_cid=, wzrk_rnv=false, wzrk_ttl=1724863031, wzrk_push_amp=false, wzrk_bc=, wzrk_bi=2,
wzrk_ck=1723000961_1724776631, wzrk_dt=FIREBASE, wzrk_id=0_0, wzrk_pn=true}]
08-27 12:37:11.826 25991 26746 V CleverTap:TEST-Z69-WWW-KI7B: rendering push on caller thread with id = 6083
08-27 12:37:11.826 25991 26746 D CleverTap:TEST-Z69-WWW-KI7B: Handling notification: Bundle[{wzrk_acct_id=TEST-Z69-WWW-KI7B, nm=msg 2, nt=title 2,
omr_invoke_time_in_millis=1724776631826, wzrk_pivot=wzrk_default, wzrk_cid=, wzrk_rnv=false, wzrk_ttl=1724863031, wzrk_push_amp=false, wzrk_bc=, wzrk_bi=2, wzrk_ck=1723000961_1724776631,
wzrk_dt=FIREBASE, wzrk_id=0_0, wzrk_pn=true}]
08-27 12:37:11.827 25991 26746 D CleverTap:TEST-Z69-WWW-KI7B: ChannelId is required for API 26+ but not provided in the notification payload. Falling to default channel:
Bundle[{wzrk_acct_id=TEST-Z69-WWW-KI7B, nm=msg 2, nt=title 2, omr_invoke_time_in_millis=1724776631826, wzrk_pivot=wzrk_default, wzrk_cid=, wzrk_rnv=false, wzrk_ttl=1724863031,
wzrk_push_amp=false, wzrk_bc=, wzrk_bi=2, wzrk_ck=1723000961_1724776631, wzrk_dt=FIREBASE, wzrk_id=0_0, wzrk_pn=true}]
08-27 12:37:11.827 25991 26746 D CleverTap:CleverTap: Missing Default CleverTap Notification Channel metadata in AndroidManifest.
08-27 12:37:11.829 25991 26746 D CleverTap:TEST-Z69-WWW-KI7B: Rendering Push on channel = fcm_fallback_notification_channel
08-27 12:37:11.829 25991 26746 V CleverTap:TEST-Z69-WWW-KI7B: Converting collapse_key: 1723000961_1724776631 to notificationId int: 538630010
08-27 12:37:11.829 25991 26746 D CleverTap:TEST-Z69-WWW-KI7B: Creating the notification id: 538630010 from collapse_key: 1723000961_1724776631
08-27 12:37:11.838 25991 26746 V CleverTap: handling bitmap download request in BitmapDownloadRequestHandlerWithTimeLimit....
08-27 12:37:11.839 25991 26747 V CleverTap: handling bitmap download request in NotificationBitmapDownloadRequestHandler....
08-27 12:37:11.840 25991 26747 W System.err:    at com.clevertap.android.sdk.Utils.getAppIcon(Utils.java:464)
08-27 12:37:11.840 25991 26747 W System.err:    at com.clevertap.android.sdk.Utils.getDownloadedBitmapPostFallbackIconCheck(Utils.java:250)
08-27 12:37:11.840 25991 26747 W System.err:    at com.clevertap.android.sdk.bitmap.NotificationBitmapDownloadRequestHandler.handleRequest(NotificationBitmapDownloadRequestHandler.kt:22)
08-27 12:37:11.840 25991 26747 W System.err:    at
com.clevertap.android.sdk.bitmap.BitmapDownloadRequestHandlerWithTimeLimit.handleRequest$lambda$0(BitmapDownloadRequestHandlerWithTimeLimit.kt:31)
08-27 12:37:11.840 25991 26747 W System.err:    at com.clevertap.android.sdk.bitmap.BitmapDownloadRequestHandlerWithTimeLimit.$r8$lambda$ew2Zy24Br1JCBon4UAsR42b7CBc(Unknown Source:0)
08-27 12:37:11.840 25991 26747 W System.err:    at com.clevertap.android.sdk.bitmap.BitmapDownloadRequestHandlerWithTimeLimit$$ExternalSyntheticLambda0.call(Unknown Source:4)
08-27 12:37:11.861 25991 26746 D CleverTap:TEST-Z69-WWW-KI7B: Rendered notification: Notification(channel=fcm_fallback_notification_channel shortcut=null contentView=null vibrate=null
sound=null defaults=0x0 flags=0x10 color=0x00000000 vis=PRIVATE)
08-27 12:37:11.861 25991 26746 V CleverTap: Storing Push Notification...null - with ttl - 1724863031
08-27 12:37:11.861 25991 26746 D CleverTap: Recording of Notification Viewed is disabled in the CleverTap Dashboard for notification payload: Bundle[{wzrk_acct_id=TEST-Z69-WWW-KI7B,
wzrk_bpds=NO_IMAGE, nm=msg 2, nt=title 2, omr_invoke_time_in_millis=1724776631826, wzrk_pivot=wzrk_default, wzrk_cid=, wzrk_rnv=false, wzrk_ttl=1724863031, wzrk_push_amp=false, wzrk_bc=,
wzrk_bi=2, wzrk_ck=1723000961_1724776631, wzrk_dt=FIREBASE, wzrk_id=0_0, wzrk_pn=true}]
08-27 12:37:11.870 25991 25991 D CleverTap:CTRM: received a message from Firebase
08-27 12:37:11.870 25991 25991 D CleverTap:PushProvider:  [PushType:FCM] Found Valid Notification Message
08-27 12:37:11.870 25991 25991 V CleverTap:CTRM: Notification payload does not have a fallback key.
08-27 12:37:11.870 25991 25991 V CleverTap:CTRM: got a signal to kill receiver and timer because isRenderFallback is false
08-27 12:37:11.870 25991 25991 V CleverTap:CTRM: informing OS to kill receiver...
08-27 12:37:11.871 25991 25991 V CleverTap:CTRM: informed OS to kill receiver...
08-27 12:37:11.871 25991 25991 V CleverTap:CTRM: receiver was alive for 0 seconds
```

application code:
```ts
import messaging from '@react-native-firebase/messaging'
import * as CleverTap from 'clevertap-react-native'

export function initUserTracking() {
  if (process.env.EXPO_PUBLIC_DEBUG_CLEVERTAP === 'true') {
    messaging().onMessage((remoteMessage) => {
      console.log('Received FCM message:')
      console.log(JSON.stringify(remoteMessage, null, 2))
    })
  }
  if (process.env.EXPO_PUBLIC_USER_TRACKING !== 'true') {
    CleverTap.setOptOut(true)
  }

  if (process.env.EXPO_PUBLIC_DEBUG_CLEVERTAP === 'true') {
    CleverTap.setDebugLevel(3)
  }

  CleverTap.initializeInbox()

  CleverTap.registerForPush()

  CleverTap.createNotificationChannel(
    'offersmain',
    'Offers Main Channel',
    'Main Channel for Offers Push Notifications',
    3, // apppropiate level for push marketing
    true,
  )

  CleverTap.addListener(
    CleverTap.CleverTapPushNotificationClicked,
    (e: unknown) => {
      console.log('clevertap push listener:')
      console.log(JSON.stringify(e, null, 2))
    },
  )
}
```

**Comment by Anush-Shand** [comment]
@rickmed As we can see from the logs `Found Valid Notification Message` was printed twice, does this mean the notification was sent twice. 
Also are you using a custom FirebaseMessagingService as well?
This issue is not reproducible on our [sample app](https://github.com/CleverTap/clevertap-react-native/tree/master/Example)

**Comment by rickmed** [comment]
But when the app is the background, the notification is rendered correctly (and only once). See the logs (notice how `Found Valid Notification Message` is printed twice as well)
```
08-28 10:30:11.567  8727  8727 V CleverTap:TEST-Z61-WWW-KV7Z: App in background
08-28 10:30:11.568  8727  8765 V CleverTap: PostAsyncSafely Task: activityPaused starting on...pool-10-thread-1
08-28 10:30:11.568  8727  8765 V CleverTap:TEST-Z61-WWW-KV7Z: Updated session time: 1724855411
08-28 10:30:11.568  8727  8765 V CleverTap: PostAsyncSafely Task: activityPaused executed successfully on...pool-10-thread-1
08-28 10:30:19.226 14064 14064 I CleverTap: Activity Lifecycle Callback successfully registered
08-28 10:30:19.227 14064 14064 V CleverTap: Unable to parse encryption level from the Manifest, Setting it to 0 by default
08-28 10:30:19.230 14064 14064 V CleverTap: ManifestInfo: getAccountRegion called, returning region:null
08-28 10:30:19.230 14064 14064 V CleverTap: ManifestInfo: getProxyDomain called, returning proxyDomain:null
08-28 10:30:19.230 14064 14064 V CleverTap: ManifestInfo: getSpikeyProxyDomain called, returning spikeyProxyDomain:null
08-28 10:30:19.230 14064 14064 I CleverTap: Account Region not specified in the AndroidManifest - using default region
08-28 10:30:19.233 14064 14064 V CleverTap:[:ON_USER_LOGIN:TEST-Z61-WWW-KV7Z]: Setting Profile Keys from Manifest: []
08-28 10:30:19.238 14064 14094 V CleverTap: PostAsyncSafely Task: migratingEncryptionLevel starting on...pool-10-thread-1
08-28 10:30:19.238 14064 14064 V CleverTap:TEST-Z61-WWW-KV7Z:async_deviceID: DeviceInfo() called
08-28 10:30:19.240 14064 14095 V CleverTap:TEST-Z61-WWW-KV7Z: Local Data Store Executor service: Starting task - LocalDataStore#inflateLocalProfileAsync
08-28 10:30:19.243 14064 14097 V CleverTap: ioTask Task: initDeviceID starting on...pool-9-thread-2
08-28 10:30:19.243 14064 14097 V CleverTap:TEST-Z61-WWW-KV7Z:async_deviceID: Called initDeviceID()
08-28 10:30:19.243 14064 14097 V CleverTap:TEST-Z61-WWW-KV7Z:async_deviceID: Calling _getDeviceID
08-28 10:30:19.244 14064 14096 V CleverTap: ioTask Task: getDeviceCachedInfo starting on...pool-9-thread-1
08-28 10:30:19.245 14064 14098 V CleverTap: ioTask Task: buildCache starting on...pool-9-thread-3
08-28 10:30:19.253 14064 14095 V CleverTap:TEST-Z61-WWW-KV7Z: Local Data Store - Inflated local profile {Email=rickmedina85@hotmail.com, Identity=46, Name=Ric Test}
08-28 10:30:19.255 14064 14100 V CleverTap: ioTask Task: initStores starting on...pool-9-thread-4
08-28 10:30:19.256 14064 14102 V CleverTap: ioTask Task: initCTVariables starting on...pool-9-thread-6
08-28 10:30:19.256 14064 14102 D CleverTap:variables: init() called
08-28 10:30:19.261 14064 14101 V CleverTap: ioTask Task: initFCManager starting on...pool-9-thread-5
08-28 10:30:19.261 14064 14103 V CleverTap: ioTask Task: initFeatureFlags starting on...pool-9-thread-7
08-28 10:30:19.264 14064 14064 V CleverTap:[:PushProvider:TEST-Z61-WWW-KV7Z]: SDK Class Available :com.google.firebase.messaging.FirebaseMessagingService
08-28 10:30:19.264 14064 14098 V CleverTap: ioTask Task: buildCache executed successfully on...pool-9-thread-3
08-28 10:30:19.264 14064 14097 V CleverTap:TEST-Z61-WWW-KV7Z:async_deviceID: Called _getDeviceID
08-28 10:30:19.264 14064 14097 V CleverTap:TEST-Z61-WWW-KV7Z: CleverTap ID already present for profile
08-28 10:30:19.264 14064 14096 D CleverTap: ExoPlayer is present
08-28 10:30:19.264 14064 14097 V CleverTap: ioTask Task: initDeviceID executed successfully on...pool-9-thread-2
08-28 10:30:19.265 14064 14064 V CleverTap:[:PushProvider:TEST-Z61-WWW-KV7Z]: SDK class Not available com.huawei.hms.push.HmsMessageService Exception:java.lang.ClassNotFoundException
08-28 10:30:19.265 14064 14094 V CleverTap: PostAsyncSafely Task: migratingEncryptionLevel executed successfully on...pool-10-thread-1
08-28 10:30:19.265 14064 14094 V CleverTap: PostAsyncSafely Task: createOrResetWorker starting on...pool-10-thread-1
08-28 10:30:19.265 14064 14094 D CleverTap:TEST-Z61-WWW-KV7Z: Pushamp - Cancelling worker as background sync is disabled or config is analytics only
08-28 10:30:19.265 14064 14102 D CleverTap:variables: VarCache loaded cache data:
08-28 10:30:19.265 14064 14102 D CleverTap:variables: {}
08-28 10:30:19.265 14064 14094 V CleverTap: PostAsyncSafely Task: createOrResetWorker executed successfully on...pool-10-thread-1
08-28 10:30:19.266 14064 14064 V CleverTap:[:PushProvider:TEST-Z61-WWW-KV7Z]: SDK class Not available com.baidu.android.pushservice.PushMessageReceiver
Exception:java.lang.ClassNotFoundException
08-28 10:30:19.266 14064 14102 D CleverTap:variables: applyVariableDiffs() called with: diffs = [{}]
08-28 10:30:19.266 14064 14102 D CleverTap:variables: applyVariableDiffs: updated value of merged=[{}]
08-28 10:30:19.266 14064 14102 V CleverTap: ioTask Task: initCTVariables executed successfully on...pool-9-thread-6
08-28 10:30:19.266 14064 14096 D CleverTap: READ_PHONE_STATE permission not asked by the app or not granted by the user
08-28 10:30:19.266 14064 14064 V CleverTap:[:PushProvider:TEST-Z61-WWW-KV7Z]: SDK class Not available com.amazon.device.messaging.ADM Exception:java.lang.ClassNotFoundException
08-28 10:30:19.267 14064 14064 V CleverTap:[:PushProvider:TEST-Z61-WWW-KV7Z]: Found provider:com.clevertap.android.sdk.pushnotification.fcm.FcmPushProvider
08-28 10:30:19.267 14064 14101 V CleverTap:TEST-Z61-WWW-KV7Z:async_deviceID: Initializing InAppFC with device Id = __a5e2b44e7b0f4aed8f7ab0f40a54febf
08-28 10:30:19.267 14064 14094 V CleverTap: PostAsyncSafely Task: asyncFindCTPushProviders starting on...pool-10-thread-1
08-28 10:30:19.268 14064 14101 V CleverTap: ioTask Task: initFCManager executed successfully on...pool-9-thread-5
08-28 10:30:19.268 14064 14064 V CleverTap:TEST-Z61-WWW-KV7Z:async_deviceID: CoreState is set
08-28 10:30:19.269 14064 14064 I CleverTap: CleverTap SDK initialized with accountId: TEST-Z61-WWW-KV7Z accountToken: 000-c61 accountRegion: null
08-28 10:30:19.269 14064 14103 V CleverTap:TEST-Z61-WWW-KV7Z:async_deviceID: Initializing Feature Flags with device Id = __a5e2b44e7b0f4aed8f7ab0f40a54febf
08-28 10:30:19.269 14064 14064 V CleverTap:TEST-Z61-WWW-KV7Z:async_deviceID: CleverTapAPI instance = com.clevertap.android.sdk.CleverTapAPI@c8606bb
08-28 10:30:19.269 14064 14064 V CleverTap: Lifecycle callbacks have already been registered
08-28 10:30:19.269 14064 14064 V CleverTap:TEST-Z61-WWW-KV7Z:async_deviceID: CleverTapAPI instance = com.clevertap.android.sdk.CleverTapAPI@c8606bb
08-28 10:30:19.271 14064 14103 V CleverTap:TEST-Z61-WWW-KV7Z:async_deviceID: Feature Flags initialized
08-28 10:30:19.271 14064 14106 V CleverTap: ioTask Task: initFeatureFlags starting on...pool-9-thread-8
08-28 10:30:19.272 14064 14106 V CleverTap:TEST-Z61-WWW-KV7Z[Feature Flag]: Feature flags init is called
08-28 10:30:19.273 14064 14103 V CleverTap: ioTask Task: initFeatureFlags executed successfully on...pool-9-thread-7
08-28 10:30:19.274 14064 14100 V CleverTap: ioTask Task: initStores executed successfully on...pool-9-thread-4
08-28 10:30:19.275 14064 14106 V CleverTap:TEST-Z61-WWW-KV7Z: [Exception While Reading:
/data/user/0/com.tiigre/files/Feature_Flag_TEST-Z61-WWW-KV7Z___a5e2b44e7b0f4aed8f7ab0f40a54febf/ff_cache.json: open failed: ENOENT (No such file or directory)
08-28 10:30:19.276 14064 14106 V CleverTap:TEST-Z61-WWW-KV7Z[Feature Flag]: Feature flags file is empty-Feature_Flag_TEST-Z61-WWW-KV7Z___a5e2b44e7b0f4aed8f7ab0f40a54febf/ff_cache.json
08-28 10:30:19.276 14064 14106 V CleverTap: ioTask Task: initFeatureFlags executed successfully on...pool-9-thread-8
08-28 10:30:19.281 14064 14096 V CleverTap: ioTask Task: getDeviceCachedInfo executed successfully on...pool-9-thread-1
08-28 10:30:19.282 14064 14094 V CleverTap:[:PushProvider:TEST-Z61-WWW-KV7Z]: Available Provider: class com.clevertap.android.sdk.pushnotification.fcm.FcmPushProvider
08-28 10:30:19.282 14064 14094 V CleverTap: PostAsyncSafely Task: asyncFindCTPushProviders executed successfully on...pool-10-thread-1
08-28 10:30:19.283 14064 14094 V CleverTap: PostAsyncSafely Task: initInAppFCManager starting on...pool-10-thread-1
08-28 10:30:19.283 14064 14094 V CleverTap:TEST-Z61-WWW-KV7Z:async_deviceID: InAppFCManager init() called
08-28 10:30:19.288 14064 14094 V CleverTap: PostAsyncSafely Task: initInAppFCManager executed successfully on...pool-10-thread-1
08-28 10:30:19.288 14064 14094 V CleverTap: PostAsyncSafely Task: CleverTapAPI#initializeDeviceInfo starting on...pool-10-thread-1
08-28 10:30:19.288 14064 14094 V CleverTap: PostAsyncSafely Task: Manifest Validation starting on...pool-10-thread-1
08-28 10:30:19.290 14064 14094 I CleverTap: SDK Version Code is 60201
08-28 10:30:19.293 14064 14094 I CleverTap: sdk.pushnotification.CTPushNotificationReceiver is present
08-28 10:30:19.296 14064 14094 I CleverTap: pushnotification.CTNotificationIntentService not present
08-28 10:30:19.301 14064 14094 I CleverTap: InAppNotificationActivity is present
08-28 10:30:19.302 14064 14094 I CleverTap: inbox.CTInboxActivity is present
08-28 10:30:19.303 14064 14094 I CleverTap: geofence.CTGeofenceReceiver not present
08-28 10:30:19.303 14064 14094 I CleverTap: geofence.CTLocationUpdateReceiver not present
08-28 10:30:19.303 14064 14094 I CleverTap: geofence.CTGeofenceBootReceiver not present
08-28 10:30:19.304 14064 14094 I CleverTap: pushnotification.fcm.FcmMessageListenerService is present
08-28 10:30:19.304 14064 14094 V CleverTap: PostAsyncSafely Task: Manifest Validation executed successfully on...pool-10-thread-1
08-28 10:30:19.304 14064 14094 V CleverTap: PostAsyncSafely Task: CleverTapAPI#initializeDeviceInfo executed successfully on...pool-10-thread-1
08-28 10:30:19.304 14064 14094 V CleverTap: PostAsyncSafely Task: setStatesAsync starting on...pool-10-thread-1
08-28 10:30:19.309 14064 14094 V CleverTap:TEST-Z61-WWW-KV7Z: Setting device network info reporting state from storage to false
08-28 10:30:19.309 14064 14094 V CleverTap:TEST-Z61-WWW-KV7Z: Set current user OptOut state from storage to: false for key: OptOut:__a5e2b44e7b0f4aed8f7ab0f40a54febf
08-28 10:30:19.310 14064 14094 V CleverTap: PostAsyncSafely Task: setStatesAsync executed successfully on...pool-10-thread-1
08-28 10:30:19.310 14064 14094 V CleverTap: PostAsyncSafely Task: saveConfigtoSharedPrefs starting on...pool-10-thread-1
08-28 10:30:19.312 14064 14094 V CleverTap: PostAsyncSafely Task: saveConfigtoSharedPrefs executed successfully on...pool-10-thread-1
08-28 10:30:19.313 14064 14094 V CleverTap: PostAsyncSafely Task: recordDeviceIDErrors starting on...pool-10-thread-1
08-28 10:30:19.313 14064 14094 V CleverTap: PostAsyncSafely Task: recordDeviceIDErrors executed successfully on...pool-10-thread-1
08-28 10:30:20.377 14064 14064 V CleverTap:TEST-Z61-WWW-KV7Z:async_deviceID: DeviceID initialized successfully!Thread[main,5,main]
08-28 10:30:20.377 14064 14064 V CleverTap:TEST-Z61-WWW-KV7Z:async_deviceID: CleverTapAPI instance = com.clevertap.android.sdk.CleverTapAPI@c8606bb
08-28 10:30:20.377 14064 14064 V CleverTap:TEST-Z61-WWW-KV7Z:async_deviceID: Got device id from DeviceInfo, notifying user profile initialized to SyncListener
08-28 10:30:20.416 14064 14153 D CleverTap:PushProvider:  [PushType:FCM] Found Valid Notification Message
08-28 10:30:20.417 14064 14153 V CleverTap:[:PushProvider:TEST-Z61-WWW-KV7Z]:  [PushType:FCM] received notification from CleverTap: Bundle[{wzrk_acct_id=TEST-Z61-WWW-KV7Z, nm=hola 3,
nt=hola 3, omr_invoke_time_in_millis=1724855420416, wzrk_pivot=wzrk_default, wzrk_cid=, wzrk_rnv=false, wzrk_ttl=1724941818, wzrk_push_amp=false, wzrk_bc=, wzrk_bi=2,
wzrk_ck=1723000961_1724855418, wzrk_dt=FIREBASE, wzrk_id=0_0, wzrk_pn=true}]
08-28 10:30:20.418 14064 14153 V CleverTap:TEST-Z61-WWW-KV7Z: rendering push on caller thread with id = 25986
08-28 10:30:20.418 14064 14153 D CleverTap:TEST-Z61-WWW-KV7Z: Handling notification: Bundle[{wzrk_acct_id=TEST-Z61-WWW-KV7Z, nm=hola 3, nt=hola 3,
omr_invoke_time_in_millis=1724855420416, wzrk_pivot=wzrk_default, wzrk_cid=, wzrk_rnv=false, wzrk_ttl=1724941818, wzrk_push_amp=false, wzrk_bc=, wzrk_bi=2, wzrk_ck=1723000961_1724855418,
wzrk_dt=FIREBASE, wzrk_id=0_0, wzrk_pn=true}]
08-28 10:30:20.419 14064 14153 D CleverTap:TEST-Z61-WWW-KV7Z: ChannelId is required for API 26+ but not provided in the notification payload. Falling to default channel:
Bundle[{wzrk_acct_id=TEST-Z61-WWW-KV7Z, nm=hola 3, nt=hola 3, omr_invoke_time_in_millis=1724855420416, wzrk_pivot=wzrk_default, wzrk_cid=, wzrk_rnv=false, wzrk_ttl=1724941818,
wzrk_push_amp=false, wzrk_bc=, wzrk_bi=2, wzrk_ck=1723000961_1724855418, wzrk_dt=FIREBASE, wzrk_id=0_0, wzrk_pn=true}]
08-28 10:30:20.419 14064 14153 D CleverTap:CleverTap: Missing Default CleverTap Notification Channel metadata in AndroidManifest.
08-28 10:30:20.423 14064 14153 D CleverTap:TEST-Z61-WWW-KV7Z: Rendering Push on channel = fcm_fallback_notification_channel
08-28 10:30:20.424 14064 14153 V CleverTap:TEST-Z61-WWW-KV7Z: Converting collapse_key: 1723000961_1724855418 to notificationId int: 565380351
08-28 10:30:20.424 14064 14153 D CleverTap:TEST-Z61-WWW-KV7Z: Creating the notification id: 565380351 from collapse_key: 1723000961_1724855418
08-28 10:30:20.429 14064 14153 V CleverTap: handling bitmap download request in BitmapDownloadRequestHandlerWithTimeLimit....
08-28 10:30:20.430 14064 14156 V CleverTap: handling bitmap download request in NotificationBitmapDownloadRequestHandler....
08-28 10:30:20.432 14064 14156 W System.err:    at com.clevertap.android.sdk.Utils.getAppIcon(Utils.java:464)
08-28 10:30:20.432 14064 14156 W System.err:    at com.clevertap.android.sdk.Utils.getDownloadedBitmapPostFallbackIconCheck(Utils.java:250)
08-28 10:30:20.432 14064 14156 W System.err:    at com.clevertap.android.sdk.bitmap.NotificationBitmapDownloadRequestHandler.handleRequest(NotificationBitmapDownloadRequestHandler.kt:22)
08-28 10:30:20.433 14064 14156 W System.err:    at
com.clevertap.android.sdk.bitmap.BitmapDownloadRequestHandlerWithTimeLimit.handleRequest$lambda$0(BitmapDownloadRequestHandlerWithTimeLimit.kt:31)
08-28 10:30:20.433 14064 14156 W System.err:    at com.clevertap.android.sdk.bitmap.BitmapDownloadRequestHandlerWithTimeLimit.$r8$lambda$ew2Zy24Br1JCBon4UAsR42b7CBc(Unknown Source:0)
08-28 10:30:20.433 14064 14156 W System.err:    at com.clevertap.android.sdk.bitmap.BitmapDownloadRequestHandlerWithTimeLimit$$ExternalSyntheticLambda0.call(Unknown Source:4)
08-28 10:30:20.457 14064 14153 D CleverTap:TEST-Z61-WWW-KV7Z: Rendered notification: Notification(channel=fcm_fallback_notification_channel shortcut=null contentView=null vibrate=null
sound=null defaults=0x0 flags=0x10 color=0x00000000 vis=PRIVATE)
08-28 10:30:20.457 14064 14153 V CleverTap: Storing Push Notification...null - with ttl - 1724941818
08-28 10:30:20.457 14064 14153 D CleverTap: Recording of Notification Viewed is disabled in the CleverTap Dashboard for notification payload: Bundle[{wzrk_acct_id=TEST-Z61-WWW-KV7Z,
wzrk_bpds=NO_IMAGE, nm=hola 3, nt=hola 3, omr_invoke_time_in_millis=1724855420416, wzrk_pivot=wzrk_default, wzrk_cid=, wzrk_rnv=false, wzrk_ttl=1724941818, wzrk_push_amp=false, wzrk_bc=,
wzrk_bi=2, wzrk_ck=1723000961_1724855418, wzrk_dt=FIREBASE, wzrk_id=0_0, wzrk_pn=true}]
08-28 10:30:20.472 14064 14064 D CleverTap:CTRM: received a message from Firebase
08-28 10:30:20.473 14064 14064 D CleverTap:PushProvider:  [PushType:FCM] Found Valid Notification Message
08-28 10:30:20.474 14064 14064 V CleverTap:CTRM: Notification payload does not have a fallback key.
08-28 10:30:20.474 14064 14064 V CleverTap:CTRM: got a signal to kill receiver and timer because isRenderFallback is false
08-28 10:30:20.474 14064 14064 V CleverTap:CTRM: informing OS to kill receiver...
08-28 10:30:20.474 14064 14064 V CleverTap:CTRM: informed OS to kill receiver...
08-28 10:30:20.474 14064 14064 V CleverTap:CTRM: receiver was alive for 0 seconds
```

Also, can you clarify about 
> Also are you using a custom FirebaseMessagingService as well?

and how it could be related?

Thank you very much for your help!

**Comment by rickmed** [comment]
Nevermind. Issue fixed.

**Comment by Anush-Shand** [comment]
@rickmed I am glad this is resolved. Can you point out what exactly was the issue?

**Comment by rickmed** [comment]
The empty (additional) notification was this code trying to render (notification handling of other part of app):
```ts
Notifications.setNotificationHandler({
  handleNotification: async (p) => {
  },
})
```

**Comment by Anush-Shand** [comment]
Thanks 
Could you confirm if this is also fixed as a part of this? https://github.com/CleverTap/clevertap-react-native/issues/402

**Comment by rickmed** [comment]
it is not fixed (the `CleverTap.CleverTapPushNotificationClicked` notification callback being called).
